name: Automated API tests using Postman CLI 2

on: 
  push:
  workflow_dispatch:

env:
  APPROVE: false

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello, World!"
        
  ubuntu-tests:
    needs: say_hello
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests on Ubuntu
        run: |
          postman collection run "32090335-29d259b1-fc34-45ed-96b1-694f7139ca93" -e "32090335-e6198264-c4b3-4bfa-bf2a-1e05bc3b12c5" --integration-id "176094-${{ github.run_id }}"
          postman collection run "32090335-6db3cb94-2b0f-472e-92ab-7899aa667dec" -e "32090335-e6198264-c4b3-4bfa-bf2a-1e05bc3b12c5" --integration-id "176094-${{ github.run_id }}"
          postman collection run "32090335-6587613e-6769-4852-99bf-49b00da4c354" -e "32090335-e6198264-c4b3-4bfa-bf2a-1e05bc3b12c5" --integration-id "176094-${{ github.run_id }}"
          postman api lint d2603762-4e40-4c13-bbb0-f625679ebcce --integration-id 176094

  manual-approval:
    needs: ubuntu-tests
    runs-on: ubuntu-latest
    outputs:
      APPROVE: ${{steps.approval.outputs.approved}}
    steps:
      - name: Wait for approval
        id: approval
        uses: ekeel/approval-action@v1.0.3
        with:
          token: ${{ secrets.PAT_TOKEN }}
          approvers: "quinnhu99"
          approveWords: "approve, approved"
          rejectWords: "deny, denied, reject, rejected"
          issueTitle: "Manual Approval Required"
          issueBody: "This is a manual test approval. Please approve or deny this workflow."
          issueLabels: "Manual Approval Required"
      - name: Get the output
        run: |
          echo "Approved: ${{ steps.approval.outputs.approved }}"
          

  macos-tests:
    needs: manual-approval
    if: needs.manual-approval.outputs.APPROVE == 'true'
    runs-on: macos-latest 
    steps:
      - uses: actions/checkout@v4
      - name: Print output
        run: |
          echo "Received: ${{needs.manual-approval.outputs.APPROVE}} == true"
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/osx_64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "32090335-29d259b1-fc34-45ed-96b1-694f7139ca93" -e "32090335-e6198264-c4b3-4bfa-bf2a-1e05bc3b12c5" --integration-id "176094-${{ github.run_id }}"
          postman collection run "32090335-6db3cb94-2b0f-472e-92ab-7899aa667dec" -e "32090335-e6198264-c4b3-4bfa-bf2a-1e05bc3b12c5" --integration-id "176094-${{ github.run_id }}"
          postman collection run "32090335-6587613e-6769-4852-99bf-49b00da4c354" -e "32090335-e6198264-c4b3-4bfa-bf2a-1e05bc3b12c5" --integration-id "176094-${{ github.run_id }}"
          postman api lint d2603762-4e40-4c13-bbb0-f625679ebcce --integration-id 176094
